<header>
    <nav>
        <ul>
            <li>
                <a href="/php/bre01-php-j2/require/?route=home">Accueil</a>
            </li>
            <li>
                <a href="/php/bre01-php-j2/require/?route=about">À propos</a>
            </li>
            <li>
                <a href="/php/bre01-php-j2/require/?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>