<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <title>Exercice require</title>
    <link rel="stylesheet" href="assets/style.css" />
</head>
<body>
    <?php require "header.phtml"; ?>
    <?php
    if (isset($route)) {
        if ($route === "contact") {
            require "contact.phtml";
        } elseif ($route === "about") {
            require "about.phtml";
        } else {
            require "home.phtml";
        }
    } else {
        require "home.phtml";
    }

    require "footer.phtml";
    ?>
</body>
</html>
