<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calculator</title>
</head>
<body>
     <?php
     include "index.php";
    if (isset($result)) {
        echo "<p>Result: $result</p>";
    }
    ?>
    <form action="index.php" method="POST">
        <label for="nb1">Number 1</label>
        <input type="number" id="nb1" name="nb1">
        <select name="operation" id="operation">
            <option value="*">*</option>
            <option value="/">/</option>
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="%">%</option>
        </select>
        <label for="nb2">Number 2</label>
        <input type="number" id="nb2" name="nb2">
        <button type="submit">Calculate</button>
    </form>
</body>
</html>